const Solutions = [
    "cries",
    "plays",
    "haste",
    "caste",
    "Abuse",
    "Adult",
    "Agent",
    "Anger",
    "Apple",
    "Award",
    "Basis",
    "Beach",
    "Birth",
    "Block",
    "Blood",
    "Board",
    "Brain",
    "Bread",
    "Break",
    "Brown",
    "Buyer",
    "Cause",
    "Chain",
    "Chair",
    "Chest",
    "Chief",
    "Child",
    "China",
    "Claim",
    "Class",
    "Clock",
    "Coach",
    "Coast",
    "Court",
    "Cover",
    "Cream",
    "Crime",
    "Cross",
    "Crowd",
    "Crown",
    "Cycle",
    "Dance",
    "Death",
    "Depth",
    "Doubt",
    "Draft",
    "Drama",
    "Dream",
    "Dress",
    "Drink",
    "Drive",
    "Earth",
    "Enemy",
    "Entry",
    "Error",
    "Event",
    "Faith",
    "Fault",
    "Field",
    "Fight",
    "Final",
    "Floor",
    "Focus",
    "Force",
    "Frame",
    "Frank",
    "Front",
    "Fruit",
    "Glass",
    "Grant",
    "Grass",
    "Green",
    "Group",
    "Guide",
    "Heart",
    "Henry",
    "Horse",
    "Hotel",
    "House",
    "Image",
    "Index",
    "Input",
    "Issue",
    "Japan",
    "Jones",
    "Judge",
    "Knife",
    "Laura",
    "Layer",
    "Level",
    "Lewis",
    "Light",
    "Limit",
    "Lunch",
    "Major",
    "March",
    "Match",
    "Metal",
    "Model",
    "Money",
    "Month",
    "Motor",
    "Mouth",
    "Music",
    "Night",
    "Noise",
    "North",
    "Novel",
    "Nurse",
    "Offer",
    "Order",
    "Other",
    "Owner",
    "Panel",
    "Paper",
    "Party",
    "Peace",
    "Peter",
    "Phase",
    "Phone",
    "Piece",
    "Pilot",
    "Pitch",
    "Place",
    "Plane",
    "Plant",
    "Plate",
    "Point",
    "Pound",
    "Power",
    "Press",
    "Price",
    "Pride",
    "Prize",
    "Proof",
    "Queen",
    "Radio",
    "Range",
    "Ratio",
    "Reply",
    "Right",
    "River",
    "Round",
    "Route",
    "Rugby",
    "Scale",
    "Scene",
    "Scope",
    "Score",
    "Sense",
    "Shape",
    "Share",
    "Sheep",
    "Sheet",
    "Shift",
    "Shirt",
    "Shock",
    "Sight",
    "Simon",
    "Skill",
    "Sleep",
    "Smile",
    "Smith",
    "Smoke",
    "Sound",
    "South",
    "Space",
    "Speed",
    "Spite",
    "Sport",
    "Squad",
    "Staff",
    "Stage",
    "Start",
    "State",
    "Steam",
    "Steel",
    "Stock",
    "Stone",
    "Store",
    "Study",
    "Stuff",
    "Style",
    "Sugar",
    "Table",
    "Taste",
    "Terry",
    "Theme",
    "Thing",
    "Title",
    "Total",
    "Touch",
    "Tower",
    "Track",
    "Trade",
    "Train",
    "Trend",
    "Trial",
    "Trust",
    "Truth",
    "Uncle",
    "Union",
    "Unity",
    "Value",
    "Video",
    "Visit",
    "Voice",
    "Waste",
    "Watch",
    "Water",
    "While",
    "White",
    "Whole",
    "Woman",
    "World",
    "Youth",
    "Alcon",
    "Aught",
    "Hella",
    "Ought",
    "Thame",
    "There",
    "Thine",
    "Thine",
    "Where",
    "Which",
    "Whose",
    "Whoso",
    "Yours",
    "Yours",
    "Admit",
    "Adopt",
    "Agree",
    "Allow",
    "Alter",
    "Apply",
    "Argue",
    "Arise",
    "Avoid",
    "Begin",
    "Blame",
    "Break",
    "Bring",
    "Build",
    "Burst",
    "Carry",
    "Catch",
    "Cause",
    "Check",
    "Claim",
    "Clean",
    "Clear",
    "Climb",
    "Close",
    "Count",
    "Cover",
    "Cross",
    "Dance",
    "Doubt",
    "Drink",
    "Drive",
    "Enjoy",
    "Enter",
    "Exist",
    "Fight",
    "Force",
    "Guess",
    "Imply",
    "Issue",
    "Judge",
    "Laugh",
    "Learn",
    "Leave",
    "Limit",
    "Marry",
    "Match",
    "Occur",
    "Offer",
    "Order",
    "Phone",
    "Place",
    "Point",
    "Press",
    "Prove",
    "Raise",
    "Reach",
    "Refer",
    "Relax",
    "Serve",
    "Shall",
    "Share",
    "Shift",
    "Shoot",
    "Sleep",
    "Solve",
    "Sound",
    "Speak",
    "Spend",
    "Split",
    "Stand",
    "Start",
    "State",
    "Stick",
    "Study",
    "Teach",
    "Thank",
    "Think",
    "Throw",
    "Touch",
    "Train",
    "Treat",
    "Trust",
    "Visit",
    "Voice",
    "Waste",
    "Watch",
    "Worry",
    "Would",
    "Write",
    "Above",
    "Acute",
    "Alive",
    "Alone",
    "Angry",
    "Aware",
    "Awful",
    "Basic",
    "Black",
    "Blind",
    "Brave",
    "Brief",
    "Broad",
    "Brown",
    "Cheap",
    "Chief",
    "Civil",
    "Clean",
    "Clear",
    "Close",
    "Crazy",
    "Daily",
    "Dirty",
    "Early",
    "Empty",
    "Equal",
    "Exact",
    "Extra",
    "Faint",
    "False",
    "Fifth",
    "Final",
    "First",
    "Fresh",
    "Front",
    "Funny",
    "Giant",
    "Grand",
    "Great",
    "Green",
    "Gross",
    "Happy",
    "Harsh",
    "Heavy",
    "Human",
    "Ideal",
    "Inner",
    "Joint",
    "Large",
    "Legal",
    "Level",
    "Light",
    "Local",
    "Loose",
    "Lucky",
    "Magic",
    "Major",
    "Minor",
    "Moral",
    "Naked",
    "Nasty",
    "Naval",
    "Other",
    "Outer",
    "Plain",
    "Prime",
    "Prior",
    "Proud",
    "Quick",
    "Quiet",
    "Rapid",
    "Ready",
    "Right",
    "Roman",
    "Rough",
    "Round",
    "Royal",
    "Rural",
    "Sharp",
    "Sheer",
    "Short",
    "Silly",
    "Sixth",
    "Small",
    "Smart",
    "Solid",
    "Sorry",
    "Spare",
    "Steep",
    "Still",
    "Super",
    "Sweet",
    "Thick",
    "Third",
    "Tight",
    "Total",
    "Tough",
    "Upper",
    "Upset",
    "Urban",
    "Usual",
    "Vague",
    "Valid",
    "Vital",
    "White",
    "Whole",
    "Wrong",
    "Young",
    "Aback",
    "Abaft",
    "Aboon",
    "About",
    "Above",
    "Accel",
    "Adown",
    "Afoot",
    "Afore",
    "Afoul",
    "After",
    "Again",
    "Agape",
    "Agogo",
    "Agone",
    "Ahead",
    "Ahull",
    "Alife",
    "Alike",
    "Aline",
    "Aloft",
    "Alone",
    "Along",
    "Aloof",
    "Aloud",
    "Amiss",
    "Amply",
    "Amuck",
    "Apace",
    "Apart",
    "Aptly",
    "Arear",
    "Aside",
    "Askew",
    "Awful",
    "Badly",
    "Bally",
    "Below",
    "Canny",
    "Cheap",
    "Clean",
    "Clear",
    "Coyly",
    "Daily",
    "Dimly",
    "Dirty",
    "Ditto",
    "Drily",
    "Dryly",
    "Dully",
    "Early",
    "Extra",
    "False",
    "Fatly",
    "Feyly",
    "First",
    "Fitly",
    "Forte",
    "Forth",
    "Fresh",
    "Fully",
    "Funny",
    "Gaily",
    "Gayly",
    "Godly",
    "Great",
    "Haply",
    "Heavy",
    "Hella",
    "Hence",
    "Hotly",
    "Icily",
    "Infra",
    "Intl.",
    "Jildi",
    "Jolly",
    "Laxly",
    "Lento",
    "Light",
    "Lowly",
    "Madly",
    "Maybe",
    "Never",
    "Newly",
    "Nobly",
    "Oddly",
    "Often",
    "Other",
    "Ought",
    "Party",
    "Piano",
    "Plain",
    "Plonk",
    "Plumb",
    "Prior",
    "Queer",
    "Quick",
    "Quite",
    "Ramen",
    "Rapid",
    "Redly",
    "Right",
    "Rough",
    "Round",
    "Sadly",
    "Secus",
    "Selly",
    "Sharp",
    "Sheer",
    "Shily",
    "Short",
    "Shyly",
    "Silly",
    "Since",
    "Sleek",
    "Slyly",
    "Small",
    "So-So",
    "Sound",
    "Spang",
    "Srsly",
    "Stark",
    "Still",
    "Stone",
    "Stour",
    "Super",
    "Tally",
    "Tanto",
    "There",
    "Thick",
    "Tight",
    "Today",
    "Tomoz",
    "Truly",
    "Twice",
    "Under",
    "Utter",
    "Verry",
    "Wanly",
    "Wetly",
    "Where",
    "Wrong",
    "Wryly",
    "Abaft",
    "Aboon",
    "About",
    "Above",
    "Adown",
    "Afore",
    "After",
    "Along",
    "Aloof",
    "Among",
    "Below",
    "Circa",
    "Cross",
    "Furth",
    "Minus",
    "Neath",
    "Round",
    "Since",
    "Spite",
    "Under",
    "Until",
    "Aargh",
    "Adieu",
    "Adios",
    "Alack",
    "Aloha",
    "Avast",
    "Bakaw",
    "Basta",
    "Begad",
    "Bless",
    "Blige",
    "Brava",
    "Bravo",
    "Bring",
    "Chook",
    "Damme",
    "Dildo",
    "Ditto",
    "Frick",
    "Fudge",
    "Golly",
    "Gratz",
    "Hallo",
    "Hasta",
    "Havoc",
    "Hella",
    "Hello",
    "Howay",
    "Howdy",
    "Hullo",
    "Huzza",
    "Jesus",
    "Kapow",
    "Loose",
    "Lordy",
    "Marry",
    "Mercy",
    "Night",
    "Plonk",
    "Psych",
    "Quite",
    "Salve",
    "Skoal",
    "Sniff",
    "Sooey",
    "There",
    "Thiam",
    "Thwap",
    "Tough",
    "Twirp",
    "Viola",
    "Vivat",
    "Wacko",
    "Wahey",
    "Whist",
    "Wilma",
    "Wirra",
    "Woops",
    "Wowie",
    "Yecch",
    "Yeeha",
    "Yeesh",
    "Yowch",
    "Zowie"
];

const WORD = Solutions[Math.floor(Math.random()*Solutions.length)].toLowerCase();
const ALPHANUMERICS = "1234567890poiuytrewqasdfghjklmnbvcxz";

const EndGameMessage= {
    "1": "Unbelievable!",
    "2": "Incredible!",
    "3": "Splendid!",
    "4": "Good job!",
    "5": "Not bad!",
    "6": "Clutch!",
    "7": `The correct word was ${WORD}!`,
}

const SAVESTRING = "VERBLE_SAVE_FILE";
let Iterator = 0;
let VerblePosition = 1;
let IsGameActive = true;

function addAttempt(){
    Iterator++;
    let container = document.createElement("div");
    container.classList.add("container");
    let attempt = document.createElement("div");
    attempt.classList.add("d-flex", "justify-content-center");
    let iterator = 1;
    while (iterator < 6){
        let letter = document.createElement("div");
        letter.classList.add("solution-letter", "p-2", "m-1", "text-center", "border", "bg-dark", "text-white");
        letter.id = `letter-${Iterator}-${iterator}`;
        letter.onpaste = () => {
            return false;
        }
        letter.ondrop = () => {
            return false;
        }
        attempt.appendChild(letter);
        iterator++;
    }
    container.appendChild(attempt);
    document.getElementById("attempts").appendChild(container);
}

function clickLetter(letter){
    document.getElementById(`letter-${Iterator}-${VerblePosition}`).textContent = letter
    if (VerblePosition < 5){
        VerblePosition++;
    }
}

function deleteLetter(){
    document.getElementById(`letter-${Iterator}-${VerblePosition}`).textContent = '';
    if (VerblePosition > 1){
        VerblePosition--;
    }
}

function check(){
    const lastChild = document.getElementById("attempts").lastChild;
    var thing = lastChild.querySelectorAll(".solution-letter");
    let guess = '';
    thing.forEach(letter => {
        guess += letter.textContent;
    })
    guess = guess.toLowerCase();
    console.log(guess);
    let word = WORD.toLowerCase();
    let currentWord = word;
    if (Solutions.map(word => word.toLowerCase()).includes(guess)){  
        let iterator = 0
        thing.forEach(letter => {
            const letterButton = document.querySelector(`#${letter.textContent}`);
            if (word[iterator] === letter.textContent){
                letter.classList.remove("bg-dark")
                letter.classList.add("bg-success");
                letterButton.classList.remove("btn-light", "bg-warning", "btn-dark", "border", "border-warning");
                letterButton.classList.add("bg-success", "border-success");
            }
            else if (currentWord.includes(letter.textContent)){
                letter.classList.remove("bg-dark")
                letter.classList.add("bg-warning");
                if (!letterButton.classList.contains("bg-success")){
                    letterButton.classList.remove("btn-light", "btn-dark", "border");
                    letterButton.classList.add("bg-warning", "border-warning");
                }
            }
            else {
                if (!(letterButton.classList.contains("bg-success") || letterButton.classList.contains("bg-warning"))){
                    document.querySelector(`#${letter.textContent}`).classList.remove("btn-light");
                    document.querySelector(`#${letter.textContent}`).classList.add("btn-dark", "border");
                }
            }
            currentWord = currentWord.replace(letter.textContent, "");
            letter.disabled = true;
            iterator++;
        })
        if (guess == WORD){
            addResultToSave(Iterator.toString());
            return;
        }
        else if (Iterator === 6){
            addResultToSave("7");
            return;
        }
        addAttempt();
        VerblePosition = 1;
    }
    else {
        document.querySelector("#invalid .toast-body span").textContent = `${guess} is not a valid Verble word`;
        $("#invalid").toast('show');
    }
}

const addResultToSave = (counter) => {
    document.querySelectorAll(".d-flex.justify-content-center button").forEach(button => {
        button.disabled = true;
    })
    window.onkeydown = () => false;
    let save = getSave();
    if (!save){
        save = {
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 0,
            "5": 0,
            "6": 0,
            "7": 0,
        }
    }

    save[counter]++;
    localStorage.setItem(SAVESTRING, JSON.stringify(save));
    IsGameActive = false;
    postResults(counter);
}

function postResults(counter){
    const save = getSave();
    if (save){
        const sum = Object.values(save).reduce((a, b) => a + b);
        console.log(EndGameMessage[counter]);
        document.querySelector("#end-game .modal-title").textContent = EndGameMessage[counter];
        for (attempt in save){
            const nextPart = `${attempt === "7" ? "fail" : attempt}: ${Math.round(save[attempt]*10000/sum)/100}%`
            console.log(nextPart);
            const div = document.createElement("div");
            div.textContent = nextPart;
            div.classList.add("text-dark");
            document.querySelector("#end-game .modal-body").appendChild(div);
        }
        (new bootstrap.Modal(document.getElementById('end-game'))).show()
    }
}

function getSave(){
    return JSON.parse(localStorage.getItem(SAVESTRING));
}

$(window).keydown(e => {
    if (IsGameActive){
        if (e.key === "Enter"){
            check();
        }
        if (e.key === "Backspace" || e.key === "Delete"){
            deleteLetter();
        }
        if (ALPHANUMERICS.includes(e.key)){
            clickLetter(e.key);
        }
    }
})

window.onload = () => {
    addAttempt();
}